CREATE TABLE MODELO (
	ID_MODELO INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO),
	CONSTRAINT UK_MODELO UNIQUE (NOMBRE)
	)
GO

CREATE TABLE MARCA (
	ID_MARCA INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA),
	CONSTRAINT UK_MARCA UNIQUE (NOMBRE)
	)
GO

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
	CONSTRAINT UK_CATEGORIA UNIQUE (NOMBRE)
	)
GO

CREATE TABLE SUBCATEGORIA (
	ID_SUBCATEGORIA INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	CONSTRAINT PK_SUBCATEGORIA PRIMARY KEY (ID_SUBCATEGORIA),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT UK_SUBCATEGORIA UNIQUE (NOMBRE, ID_CATEGORIA)
	)
GO

CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL,
	TIPO_DISPONIBILIDAD VARCHAR(30) NOT NULL,
	ID_MARCA INT NOT NULL,
	ID_SUBCATEGORIA INT NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
	CONSTRAINT FK_SUBCATEGORIA FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
	CONSTRAINT UK_PRODUCTO UNIQUE (NOMBRE)
	)
GO

CREATE TABLE EMPRESA (
	ID_EMPRESA INT NOT NULL IDENTITY,
	NOMBRE VARCHAR(30) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(30) NOT NULL,
	CUIL VARCHAR(30) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA),
	CONSTRAINT UK_EMPRESA UNIQUE (NOMBRE, CUIL, CORREO)
	)
GO

CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR INT NOT NULL IDENTITY,
	ID_EMPRESA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL
	CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR),
	CONSTRAINT FK_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
	)
GO
