CREATE TABLE CLIENTE (
	ID_CLIENTE INT NOT NULL IDENTITY,
	CUIL VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	PORCENTAJE_IVA DECIMAL(5,2) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT UK_CLIENTE UNIQUE (CUIL, NOMBRE, DIRECCION, PORCENTAJE_IVA)
	)
GO

CREATE TABLE ARTICULO (
	ID_ARTICULO INT NOT NULL IDENTITY,
	CODIGO VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	PRECIO_UNITARIO MONEY NOT NULL,
	CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),
	CONSTRAINT UK_ARTICULO UNIQUE (CODIGO, DESCRIPCION, PRECIO_UNITARIO)
	)
GO

CREATE TABLE FACTURA (
	ID_FACTURA INT NOT NULL IDENTITY,
	NUMERO INT NOT NULL,
	FECHA DATETIME NOT NULL,
	TOTAL_SIN_IMPUESTOS MONEY NOT NULL,
	IMPORTE_IVA MONEY NOT NULL,
	TOTAL_CON_IMPUESTOS MONEY NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT UK_FACTURA UNIQUE (NUMERO),
	)
GO

CREATE TABLE RENGLON (
	ID_RENGLON INT NOT NULL IDENTITY,
	CANTIDAD INT NOT NULL,
	TOTAL MONEY NOT NULL,
	ID_ARTICULO INT NOT NULL,
	ID_FACTURA INT NOT NULL,
	CONSTRAINT PK_RENGLON PRIMARY KEY (ID_RENGLON),
	CONSTRAINT FK_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO),
	CONSTRAINT FK_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
	CONSTRAINT UK_ARTICULO UNIQUE (ID_ARTICULO, ID_FACTURA)
	)
GO
