INSERT INTO MODELO (NOMBRE)
VALUES
	('Modelo1'),
	('Modelo2'),
	('Modelo3')
GO

INSERT INTO MARCA (NOMBRE) 
VALUES 
	('Marca1'), 
	('Marca2'),
	('Marca3')
GO

INSERT INTO CATEGORIA (NOMBRE) 
VALUES 
	('Categoria1'),
	('Categoria2'),
	('Categoria3') 
GO

INSERT INTO SUBCATEGORIA (NOMBRE, ID_CATEGORIA) 
VALUES 
	('Subcategoria1', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria1')),
	('Subcategoria2', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria2')),
	('Subcategoria3', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria3'))
GO

INSERT INTO PRODUCTO (NOMBRE, TIPO_DISPONIBILIDAD, ID_MARCA, ID_SUBCATEGORIA)
VALUES
	('Producto1', 'Disponible', (SELECT ID_MARCA FROM MARCA WHERE NOMBRE = 'Marca1'), (SELECT ID_SUBCATEGORIA FROM SUBCATEGORIA WHERE NOMBRE = 'Subcategoria1')),
	('Producto2', 'Disponible', (SELECT ID_MARCA FROM MARCA WHERE NOMBRE = 'Marca2'), (SELECT ID_SUBCATEGORIA FROM SUBCATEGORIA WHERE NOMBRE = 'Subcategoria2')),
	('Producto3', 'Disponible', (SELECT ID_MARCA FROM MARCA WHERE NOMBRE = 'Marca3'), (SELECT ID_SUBCATEGORIA FROM SUBCATEGORIA WHERE NOMBRE = 'Subcategoria3'))
GO
