INSERT INTO CATEGORIA (NOMBRE) VALUES ('Categoria1')
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Categoria2')
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Categoria3')
GO

INSERT INTO SUBCATEGORIA (NOMBRE, ID_CATEGORIA) VALUES ('Subcategoria1', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria1'))
INSERT INTO SUBCATEGORIA (NOMBRE, ID_CATEGORIA) VALUES ('Subcategoria2', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria2'))
INSERT INTO SUBCATEGORIA (NOMBRE, ID_CATEGORIA) VALUES ('Subcategoria3', (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = 'Categoria3'))
GO
